//! Renders the live layout as an annotated TOML document.

use crate::core::config::{ColorMode, RgbRange, Transform};
use crate::core::resolve::fmt_scale;
use crate::core::state::{PropValue, State};

/// `logical_monitors[].transform` is a `uint32` matching Wayland's
/// `wl_output.transform` / Mutter's `MetaMonitorTransform` enum, whose order
/// is exactly `Transform::ALL`'s declaration order — a stable, foundational
/// protocol enum (unlike `color-mode`/`rgb-range`'s sparse, version-varying
/// wire codes, which need their own lookup table in `core::state`), so
/// indexing into `Transform::ALL` is the whole mapping. Falls back to
/// `Normal` for any (in practice unreachable) out-of-range code.
fn transform_from_wire(code: u32) -> Transform {
    Transform::ALL
        .get(code as usize)
        .copied()
        .unwrap_or(Transform::Normal)
}

/// Ports names to TOML table-key slugs: runs of non-alphanumeric ASCII
/// collapse to one `-`, the result is lowercased and trimmed of leading or
/// trailing dashes. Falls back to `fallback` if nothing alphanumeric survives.
fn slug(text: &str, fallback: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut pending_dash = false;
    for c in text.chars() {
        if c.is_ascii_alphanumeric() {
            if pending_dash && !out.is_empty() {
                out.push('-');
            }
            pending_dash = false;
            out.push(c.to_ascii_lowercase());
        } else {
            pending_dash = true;
        }
    }
    if out.is_empty() {
        fallback.to_lowercase()
    } else {
        out
    }
}

/// Pushes `key = value` to the TOML document when `value` is a known,
/// off-default value — `Absent` or `Known(default)` mean there's nothing
/// worth writing (exactly what `gdctl` already assumes when the key is
/// omitted). `Unrecognized` means the property genuinely holds something,
/// so it's reported as a note instead of dropped: the monitor really is
/// in some non-default state, we just can't name it, so the exported
/// config would otherwise silently under-describe it.
fn push_if_non_default<T: PartialEq + std::fmt::Display>(
    lines: &mut Vec<String>,
    notes: &mut Vec<String>,
    key: &str,
    value: PropValue<T>,
    default: T,
    monitor: &str,
) {
    match value {
        PropValue::Known(value) if value != default => {
            lines.push(format!("{key} = {}", toml_string(&value.to_string())));
        }
        PropValue::Known(_) | PropValue::Absent => {}
        PropValue::Unrecognized(code) => {
            notes.push(format!(
                "{monitor} reports {key} as code {code}, which this version of haichi doesn't \
                 recognize; it was left out of the exported layout"
            ));
        }
    }
}

/// Quotes and escapes a TOML basic string.
fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0C}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 || c as u32 == 0x7F => {
                out.push_str(&format!("\\u{:04X}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Renders the live layout as a TOML document, returning `(document, notes)`.
/// Notes describe monitors or logical monitors the schema could not express
/// (mirroring, connected-but-inactive outputs, …) and belong on stderr.
pub fn export_toml(state: &State) -> (String, Vec<String>) {
    let mut notes: Vec<String> = Vec::new();
    let active: Vec<&str> = state
        .logical_monitors
        .iter()
        .flat_map(|lm| lm.specs.first())
        .map(|spec| spec.0.as_str())
        .collect();
    for monitor in &state.monitors {
        if !active.contains(&monitor.connector.as_str()) {
            notes.push(format!(
                "{} is connected but not active; it is not in the exported layout, so applying \
                 this file keeps it off",
                monitor.describe()
            ));
        }
    }

    let mut lines: Vec<String> = vec![
        "# Generated by haichi export from the live display config.".to_string(),
        "# Screens are matched on vendor/product/serial; the connector is".to_string(),
        "# resolved at apply time and is only recorded here as a comment.".to_string(),
        String::new(),
    ];
    if let Some(layout_mode) = &state.layout_mode {
        lines.push(format!("layout-mode = {}", toml_string(layout_mode)));
        lines.push(String::new());
    }

    let mut used: Vec<String> = Vec::new();

    for logical in &state.logical_monitors {
        let Some(first_spec) = logical.specs.first() else {
            continue;
        };
        if logical.specs.len() > 1 {
            let connectors: Vec<&str> = logical.specs.iter().map(|s| s.0.as_str()).collect();
            notes.push(format!(
                "a logical monitor drives {} (mirroring); this schema has no way to express \
                 that, so only {} was exported",
                connectors.join(", "),
                first_spec.0
            ));
        }

        let connector = &first_spec.0;
        let Some(monitor) = state.monitors.iter().find(|m| &m.connector == connector) else {
            notes.push(format!(
                "{connector} is in a logical monitor but not in the monitor list; skipped"
            ));
            continue;
        };

        let Some(mode) = monitor.current_mode() else {
            notes.push(format!(
                "{} reports no current mode; skipped",
                monitor.describe()
            ));
            continue;
        };

        let name = slug(&monitor.product, &monitor.connector);
        let mut candidate = name.clone();
        let mut n = 2;
        while used.contains(&candidate) {
            candidate = format!("{name}-{n}");
            n += 1;
        }
        used.push(candidate.clone());

        let label = if monitor.display_name.is_empty() {
            &monitor.product
        } else {
            &monitor.display_name
        };
        lines.push(format!("# {label} — currently on {}", monitor.connector));
        lines.push(format!("[screens.{candidate}]"));
        lines.push(format!("vendor = {}", toml_string(&monitor.vendor)));
        lines.push(format!("product = {}", toml_string(&monitor.product)));
        lines.push(format!("serial = {}", toml_string(&monitor.serial)));
        lines.push(format!("mode = {}", toml_string(&mode.id)));
        lines.push(format!("x = {}", logical.x));
        lines.push(format!("y = {}", logical.y));
        lines.push(format!("scale = {}", fmt_scale(logical.scale)));
        lines.push(format!(
            "transform = {}",
            toml_string(&transform_from_wire(logical.transform).to_string())
        ));
        if logical.primary {
            lines.push("primary = true".to_string());
        }
        // Only written when the monitor is off its default, so an export of
        // an all-SDR setup stays free of color-mode/rgb-range noise.
        push_if_non_default(
            &mut lines,
            &mut notes,
            "color-mode",
            monitor.color_mode,
            ColorMode::Default,
            &monitor.describe(),
        );
        push_if_non_default(
            &mut lines,
            &mut notes,
            "rgb-range",
            monitor.rgb_range,
            RgbRange::Auto,
            &monitor.describe(),
        );
        lines.push(String::new());
    }

    (lines.join("\n"), notes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::state::{LogicalMonitor, Mode, Monitor};

    #[test]
    fn slug_collapses_non_alphanumeric_runs_and_trims_edges() {
        assert_eq!(slug("LG SMARTGAME+", "fallback"), "lg-smartgame");
        assert_eq!(slug("P2710S", "fallback"), "p2710s");
        assert_eq!(slug("---", "fallback"), "fallback");
        assert_eq!(slug("", "Fallback"), "fallback");
    }

    #[test]
    fn toml_string_escapes_control_characters_and_quotes() {
        assert_eq!(toml_string("plain"), "\"plain\"");
        assert_eq!(toml_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(toml_string("line\nbreak"), "\"line\\nbreak\"");
    }

    #[test]
    fn transform_from_wire_matches_wayland_output_transform_order() {
        assert_eq!(transform_from_wire(0), Transform::Normal);
        assert_eq!(transform_from_wire(1), Transform::_90);
        assert_eq!(transform_from_wire(2), Transform::_180);
        assert_eq!(transform_from_wire(3), Transform::_270);
        assert_eq!(transform_from_wire(4), Transform::Flipped);
        assert_eq!(transform_from_wire(5), Transform::Flipped90);
        assert_eq!(transform_from_wire(6), Transform::Flipped180);
        assert_eq!(transform_from_wire(7), Transform::Flipped270);
        assert_eq!(transform_from_wire(99), Transform::Normal);
    }

    fn mode(id: &str) -> Mode {
        Mode {
            id: id.to_string(),
            width: 1920,
            height: 1080,
            refresh: 60.0,
            preferred_scale: 1.0,
            supported_scales: vec![1.0],
            is_current: true,
            is_preferred: false,
        }
    }

    fn monitor(connector: &str, product: &str) -> Monitor {
        Monitor {
            connector: connector.to_string(),
            vendor: "LHC".to_string(),
            product: product.to_string(),
            serial: "0".to_string(),
            display_name: String::new(),
            modes: vec![mode("1920x1080@60")],
            color_mode: PropValue::Known(ColorMode::Default),
            rgb_range: PropValue::Known(RgbRange::Auto),
        }
    }

    #[test]
    fn exports_one_screens_table_per_active_logical_monitor() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: Some("logical".to_string()),
            supports_changing_layout_mode: true,
        };

        let (document, notes) = export_toml(&state);
        assert!(notes.is_empty());
        assert!(document.contains("layout-mode = \"logical\""));
        assert!(document.contains("[screens.p2710s]"));
        assert!(document.contains("vendor = \"LHC\""));
        assert!(document.contains("primary = true"));
    }

    #[test]
    fn notes_a_connected_but_inactive_monitor() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (_, notes) = export_toml(&state);
        assert!(notes.iter().any(|n| n.contains("connected but not active")));
    }

    #[test]
    fn notes_mirroring_and_exports_only_the_first_output() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S"), monitor("DP-2", "OTHER")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![
                    (
                        "DP-1".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    ),
                    (
                        "DP-2".to_string(),
                        "LHC".to_string(),
                        "OTHER".to_string(),
                        "0".to_string(),
                    ),
                ],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, notes) = export_toml(&state);
        assert!(notes.iter().any(|n| n.contains("mirroring")));
        assert!(document.contains("[screens.p2710s]"));
        assert!(!document.contains("[screens.other]"));
    }

    #[test]
    fn deduplicates_slug_collisions() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S"), monitor("DP-2", "P2710S")],
            logical_monitors: vec![
                LogicalMonitor {
                    x: 0,
                    y: 0,
                    scale: 1.0,
                    transform: 0,
                    primary: true,
                    specs: vec![(
                        "DP-1".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    )],
                },
                LogicalMonitor {
                    x: 1920,
                    y: 0,
                    scale: 1.0,
                    transform: 0,
                    primary: false,
                    specs: vec![(
                        "DP-2".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    )],
                },
            ],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(document.contains("[screens.p2710s]"));
        assert!(document.contains("[screens.p2710s-2]"));
    }

    #[test]
    fn exports_a_non_default_color_mode_and_rgb_range() {
        let mut hdr_monitor = monitor("DP-1", "P2710S");
        hdr_monitor.color_mode = PropValue::Known(ColorMode::Bt2100);
        hdr_monitor.rgb_range = PropValue::Known(RgbRange::Full);
        let state = State {
            monitors: vec![hdr_monitor],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(document.contains("color-mode = \"bt2100\""));
        assert!(document.contains("rgb-range = \"full\""));
    }

    #[test]
    fn omits_color_mode_and_rgb_range_when_default() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(!document.contains("color-mode"));
        assert!(!document.contains("rgb-range"));
    }

    #[test]
    fn omits_color_mode_and_rgb_range_when_absent() {
        let mut absent = monitor("DP-1", "P2710S");
        absent.color_mode = PropValue::Absent;
        absent.rgb_range = PropValue::Absent;
        let state = State {
            monitors: vec![absent],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, notes) = export_toml(&state);
        assert!(!document.contains("color-mode"));
        assert!(!document.contains("rgb-range"));
        assert!(notes.is_empty());
    }

    // code-review follow-up (Copilot, PR #8): an unrecognized wire code is a
    // real, non-default value we can't name — omitted from the TOML same as
    // before, but now with a note explaining the omission instead of no
    // signal at all that something was lost.
    #[test]
    fn notes_an_unrecognized_color_mode_or_rgb_range_instead_of_silently_dropping_it() {
        let mut unrecognized = monitor("DP-1", "P2710S");
        unrecognized.color_mode = PropValue::Unrecognized(99);
        unrecognized.rgb_range = PropValue::Unrecognized(7);
        let state = State {
            monitors: vec![unrecognized],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, notes) = export_toml(&state);
        assert!(!document.contains("color-mode"));
        assert!(!document.contains("rgb-range"));
        assert!(
            notes
                .iter()
                .any(|n| n.contains("color-mode") && n.contains("99"))
        );
        assert!(
            notes
                .iter()
                .any(|n| n.contains("rgb-range") && n.contains('7'))
        );
    }
}
