//! Renders the live layout as an annotated TOML document.

use crate::core::resolve::fmt_scale;
use crate::core::state::State;

fn transform_name(code: u32) -> &'static str {
    match code {
        0 => "normal",
        1 => "90",
        2 => "180",
        3 => "270",
        4 => "flipped",
        5 => "flipped-90",
        6 => "flipped-180",
        7 => "flipped-270",
        _ => "normal",
    }
}

/// Ports names to TOML table-key slugs: runs of non-alphanumeric ASCII
/// collapse to one `-`, the result is lowercased and trimmed of leading or
/// trailing dashes. Falls back to `fallback` if nothing alphanumeric survives.
fn slug(text: &str, fallback: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut pending_dash = false;
    for c in text.chars() {
        if c.is_ascii_alphanumeric() {
            if pending_dash && !out.is_empty() {
                out.push('-');
            }
            pending_dash = false;
            out.push(c.to_ascii_lowercase());
        } else {
            pending_dash = true;
        }
    }
    if out.is_empty() {
        fallback.to_lowercase()
    } else {
        out
    }
}

/// Quotes and escapes a TOML basic string.
fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0C}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 || c as u32 == 0x7F => {
                out.push_str(&format!("\\u{:04X}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Renders the live layout as a TOML document, returning `(document, notes)`.
/// Notes describe monitors or logical monitors the schema could not express
/// (mirroring, connected-but-inactive outputs, …) and belong on stderr.
pub fn export_toml(state: &State) -> (String, Vec<String>) {
    let mut notes: Vec<String> = Vec::new();
    let active: Vec<&str> = state
        .logical_monitors
        .iter()
        .flat_map(|lm| lm.specs.first())
        .map(|spec| spec.0.as_str())
        .collect();
    for monitor in &state.monitors {
        if !active.contains(&monitor.connector.as_str()) {
            notes.push(format!(
                "{} is connected but not active; it is not in the exported layout, so applying \
                 this file keeps it off",
                monitor.describe()
            ));
        }
    }

    let mut lines: Vec<String> = vec![
        "# Generated by haichi export from the live display config.".to_string(),
        "# Screens are matched on vendor/product/serial; the connector is".to_string(),
        "# resolved at apply time and is only recorded here as a comment.".to_string(),
        String::new(),
    ];
    if let Some(layout_mode) = &state.layout_mode {
        lines.push(format!("layout-mode = {}", toml_string(layout_mode)));
        lines.push(String::new());
    }

    let mut used: Vec<String> = Vec::new();

    for logical in &state.logical_monitors {
        let Some(first_spec) = logical.specs.first() else {
            continue;
        };
        if logical.specs.len() > 1 {
            let connectors: Vec<&str> = logical.specs.iter().map(|s| s.0.as_str()).collect();
            notes.push(format!(
                "a logical monitor drives {} (mirroring); this schema has no way to express \
                 that, so only {} was exported",
                connectors.join(", "),
                first_spec.0
            ));
        }

        let connector = &first_spec.0;
        let Some(monitor) = state.monitors.iter().find(|m| &m.connector == connector) else {
            notes.push(format!(
                "{connector} is in a logical monitor but not in the monitor list; skipped"
            ));
            continue;
        };

        let Some(mode) = monitor.current_mode() else {
            notes.push(format!(
                "{} reports no current mode; skipped",
                monitor.describe()
            ));
            continue;
        };

        let name = slug(&monitor.product, &monitor.connector);
        let mut candidate = name.clone();
        let mut n = 2;
        while used.contains(&candidate) {
            candidate = format!("{name}-{n}");
            n += 1;
        }
        used.push(candidate.clone());

        let label = if monitor.display_name.is_empty() {
            &monitor.product
        } else {
            &monitor.display_name
        };
        lines.push(format!("# {label} — currently on {}", monitor.connector));
        lines.push(format!("[screens.{candidate}]"));
        lines.push(format!("vendor = {}", toml_string(&monitor.vendor)));
        lines.push(format!("product = {}", toml_string(&monitor.product)));
        lines.push(format!("serial = {}", toml_string(&monitor.serial)));
        lines.push(format!("mode = {}", toml_string(&mode.id)));
        lines.push(format!("x = {}", logical.x));
        lines.push(format!("y = {}", logical.y));
        lines.push(format!("scale = {}", fmt_scale(logical.scale)));
        lines.push(format!(
            "transform = {}",
            toml_string(transform_name(logical.transform))
        ));
        if logical.primary {
            lines.push("primary = true".to_string());
        }
        // Only written when the monitor is off its default, so an export of
        // an all-SDR setup stays free of color-mode/rgb-range noise.
        if !monitor.color_mode.is_empty() && monitor.color_mode != "default" {
            lines.push(format!("color-mode = {}", toml_string(&monitor.color_mode)));
        }
        if !monitor.rgb_range.is_empty() && monitor.rgb_range != "auto" {
            lines.push(format!("rgb-range = {}", toml_string(&monitor.rgb_range)));
        }
        lines.push(String::new());
    }

    (lines.join("\n"), notes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::state::{LogicalMonitor, Mode, Monitor};

    #[test]
    fn slug_collapses_non_alphanumeric_runs_and_trims_edges() {
        assert_eq!(slug("LG SMARTGAME+", "fallback"), "lg-smartgame");
        assert_eq!(slug("P2710S", "fallback"), "p2710s");
        assert_eq!(slug("---", "fallback"), "fallback");
        assert_eq!(slug("", "Fallback"), "fallback");
    }

    #[test]
    fn toml_string_escapes_control_characters_and_quotes() {
        assert_eq!(toml_string("plain"), "\"plain\"");
        assert_eq!(toml_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
        assert_eq!(toml_string("line\nbreak"), "\"line\\nbreak\"");
    }

    fn mode(id: &str) -> Mode {
        Mode {
            id: id.to_string(),
            width: 1920,
            height: 1080,
            refresh: 60.0,
            preferred_scale: 1.0,
            supported_scales: vec![1.0],
            is_current: true,
            is_preferred: false,
        }
    }

    fn monitor(connector: &str, product: &str) -> Monitor {
        Monitor {
            connector: connector.to_string(),
            vendor: "LHC".to_string(),
            product: product.to_string(),
            serial: "0".to_string(),
            display_name: String::new(),
            modes: vec![mode("1920x1080@60")],
            color_mode: "default".to_string(),
            rgb_range: "auto".to_string(),
        }
    }

    #[test]
    fn exports_one_screens_table_per_active_logical_monitor() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: Some("logical".to_string()),
            supports_changing_layout_mode: true,
        };

        let (document, notes) = export_toml(&state);
        assert!(notes.is_empty());
        assert!(document.contains("layout-mode = \"logical\""));
        assert!(document.contains("[screens.p2710s]"));
        assert!(document.contains("vendor = \"LHC\""));
        assert!(document.contains("primary = true"));
    }

    #[test]
    fn notes_a_connected_but_inactive_monitor() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (_, notes) = export_toml(&state);
        assert!(notes.iter().any(|n| n.contains("connected but not active")));
    }

    #[test]
    fn notes_mirroring_and_exports_only_the_first_output() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S"), monitor("DP-2", "OTHER")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![
                    (
                        "DP-1".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    ),
                    (
                        "DP-2".to_string(),
                        "LHC".to_string(),
                        "OTHER".to_string(),
                        "0".to_string(),
                    ),
                ],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, notes) = export_toml(&state);
        assert!(notes.iter().any(|n| n.contains("mirroring")));
        assert!(document.contains("[screens.p2710s]"));
        assert!(!document.contains("[screens.other]"));
    }

    #[test]
    fn deduplicates_slug_collisions() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S"), monitor("DP-2", "P2710S")],
            logical_monitors: vec![
                LogicalMonitor {
                    x: 0,
                    y: 0,
                    scale: 1.0,
                    transform: 0,
                    primary: true,
                    specs: vec![(
                        "DP-1".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    )],
                },
                LogicalMonitor {
                    x: 1920,
                    y: 0,
                    scale: 1.0,
                    transform: 0,
                    primary: false,
                    specs: vec![(
                        "DP-2".to_string(),
                        "LHC".to_string(),
                        "P2710S".to_string(),
                        "0".to_string(),
                    )],
                },
            ],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(document.contains("[screens.p2710s]"));
        assert!(document.contains("[screens.p2710s-2]"));
    }

    #[test]
    fn exports_a_non_default_color_mode_and_rgb_range() {
        let mut hdr_monitor = monitor("DP-1", "P2710S");
        hdr_monitor.color_mode = "bt2100".to_string();
        hdr_monitor.rgb_range = "full".to_string();
        let state = State {
            monitors: vec![hdr_monitor],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(document.contains("color-mode = \"bt2100\""));
        assert!(document.contains("rgb-range = \"full\""));
    }

    #[test]
    fn omits_color_mode_and_rgb_range_when_default() {
        let state = State {
            monitors: vec![monitor("DP-1", "P2710S")],
            logical_monitors: vec![LogicalMonitor {
                x: 0,
                y: 0,
                scale: 1.0,
                transform: 0,
                primary: true,
                specs: vec![(
                    "DP-1".to_string(),
                    "LHC".to_string(),
                    "P2710S".to_string(),
                    "0".to_string(),
                )],
            }],
            layout_mode: None,
            supports_changing_layout_mode: false,
        };

        let (document, _) = export_toml(&state);
        assert!(!document.contains("color-mode"));
        assert!(!document.contains("rgb-range"));
    }
}
